import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBar from '../components/Navbar'
import Footer from '../components/Footer'
import 'antd/dist/antd.css';

// import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
// import { fab } from '@fortawesome/free-brands-svg-icons'


export default function Home() {
 
  return (
    <div >
      <Head>
        <title>LUCKY IT HOUSE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/litllo.ico" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"></link>
      </Head>



      {/* <NavBar /> */}

      <div className='introcon' >
    
    

        
        
        <div className=' cardm' >
            <h1 className='title'>
              Corporate & Business Site Template By 
              <br></br>
                <span className='brand'>LUCKY IT HOUSE. </span>
                 
            </h1>
            <p  className='desc'>
                We are a digital agency that helps brands to achieve their business outcomes. We see technology as a tool to create amazing things.</p>
            <br></br>
            <button className='button' >DISCOVER</button>
        </div>
        <div className=' cardm' >
            {/* <image src="https://images.unsplash.com/photo-1521737852567-6949f3f9f2b5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=847&q=80"    /> */}
        </div>
      
    </div>









      <div className={styles.container} >
        
        <div className="our clients">

        </div>







        <div>
          <h5 className="osrvc">Latest Services</h5>
          <div className="container cg" >
            <div className="row gal" >
              <div className="col 14 s10 gal2">

                <a title="Company name and description
                description descriptiondescriptiondescriptiondescriptiondescriptiondescriptiondescriptiondescriptiondescriptiondescription"  >
                  <img className="ma" width="300px" height="200" src="https://images.unsplash.com/photo-1554415707-6e8cfc93fe23?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" />
                </a>

              </div>
              <div className="col 12 s10 gal2">
                <img className="ma" width="300px" height={200} src="https://images.pexels.com/photos/1181359/pexels-photo-1181359.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"></img>


              </div>
              <div className="col 12 s10 gal2">
                <img className="ma" width="300px" height={200} src="https://images.pexels.com/photos/1181279/pexels-photo-1181279.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"></img>


              </div>
            </div>

          </div>


          <div className="container cg" >
            
            <div className="row gal" >
              <div className="col 12 s10 gal2 ">
                <img className="ma" width="300px" height={200} src="https://images.pexels.com/photos/4974912/pexels-photo-4974912.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"></img>


              </div>
              <div className="col 12 s10 gal2">
                <img className="ma" width="300px" height={200} src="https://images.pexels.com/photos/943096/pexels-photo-943096.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"></img>


              </div>
              <div className="col 12 s10 gal2">
                <img className="ma" width="300px" height={200} src="https://images.pexels.com/photos/5473298/pexels-photo-5473298.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"></img>


              </div>
            </div>

          </div>
        </div>
        <div className="hide">
          <h3>Company name amd description</h3>
        </div>

        <div className="we-are-block">
          <h2> OUR STORY</h2>

              <div id="about-us-section">

                <div className="about-us-image">

                  <img src="https://images.unsplash.com/photo-1551434678-e076c223a692?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80" width="808" height="558" alt="Lobby Image"/>

                </div>

                <div className="about-us-info">

                  <h2>Who We Are</h2>

                  <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, look like readable English.

There are many variations of passages of Lorem Ipsum available, but the majority have in some form, by injected humour.</p>

                  <a href="#" title="About Us Button">ABOUT US</a>

                </div>

              </div>
              <br></br>

              <div id="history-section">

                <div className="history-image">

                  <img src="https://images.unsplash.com/photo-1504384308090-c894fdcc538d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80" width="951" height="671" alt="Building Pic"/>

                </div>

                <div className="history-info">

                  <h2>Our Vision</h2>

                  <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, look like readable English.

There are many variations of passages of Lorem Ipsum available, but the majority have in some form, by injected humour.</p>

                  <a href="#" title="History Button">ABOUT US</a>

                </div>

              </div>

              <div id="about-us-section">

                <div className="about-us-image">

                  <img src="https://images.unsplash.com/photo-1521737852567-6949f3f9f2b5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=847&q=80" width="808" height="558" alt="Lobby Image"/>

                </div>

                <div className="about-us-info">

                  <h2>Our History</h2>

                  <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, look like readable English.

There are many variations of passages of Lorem Ipsum available, but the majority have in some form, by injected humour.</p>

                  <a href="#" title="About Us Button">HISTORY</a>

                </div>

              </div>
              

              

        </div>
                <br></br>
                {/* our clients section */}

                <section className="client">
                    <div className="container">
                      <div className="row">

                        <div className="section-title">
                          <h2> Our Clients : </h2>
                        </div>

                        <div  className="carousel-client">
                          <div className="slide"><img src="lcvue-l.jpg" width={200} /></div>

                           <div className="slide"><img src="litllo.png" width={160} /></div>
                            <div className="slide"><img src="lcvue-l.jpg" width={200} /></div>
                        </div>
                      </div>
                    </div>
                </section>


            {/* our clients section ends */}



      </div>

      <Footer />


    </div>
  )
}
